services:
  api:
    build: .
    container_name: webhook_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL
      - DATABASE_NAME
      - COLLECTION_NAME
    networks:
      - webhook_network

networks:
  webhook_network:
    driver: bridge
